apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-dashboard
  namespace: observability-dashboard
spec:
  template:
    spec:
      containers:
        - name: observability-dashboard
          env:
            - name: LOGLEVEL
              value: 'DEBUG'
