name: Push
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

env:
  WORKLOAD_IDENTITY_PROVIDER: 'projects/363137235362/locations/global/workloadIdentityPools/github-actions-identity-pool/providers/github-actions-provider'
  SERVICE_ACCOUNT: 'sa-github-actions@agentic-layer.iam.gserviceaccount.com'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false # Ensures that if one build fails, the others will still run
      matrix:
        include:
          - name: "weather-agent"
            path: "adk/python/weather-agent"

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: 'Configure Docker for Artifact Registry'
        run: gcloud auth configure-docker eu.gcr.io

      - name: 'Docker Build'
        working-directory: ${{ matrix.path }}
        run: |
          make docker-build

      - name: 'Docker Push'
        working-directory: ${{ matrix.path }}
        run: |
          make docker-push
